import Head from 'next/head'
import React, { Suspense, useRef } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Canvas, useFrame, extend, useThree} from '@react-three/fiber'
import Box from '../components/compBox'
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";


extend({OrbitControls});

const CameraControls = () => {

  const {
    camera,
    gl: {domElement},
  } = useThree();

  const controls = useRef();
  useFrame((state) => controls.current.update());
  return <orbitControls ref={controls} args={[camera, domElement]} />;

}

export default function Home() {
  var name = {
    first: 'jake',
    last: 'mcmahon'
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button>Create</button>


      <Canvas >
        <ambientLight />
        <CameraControls />
        <pointLight position={[10, 10, 10]} />
        <Suspense fallback={null}>
        <Box position={[0, 0, 0]} scale={2} />
        </Suspense>
      </Canvas>
    </div>
  )
}
